config/routes.rb
# Rails.application.routes.draw do
MushroomObserver::Application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 get "publications/:id/destroy" => "publications#destroy"
  resources :publications

  # Default page
  root "observer#list_rss_logs"

  # Route /123 to /observer/show_observation/123.
  get ":id" => "observer#show_observation", constraints: { id: /\d+/ }

  # Short-hand notation for AJAX methods.
  get "ajax/:action/:type/:id" => "ajax", constraints: { id: /\S.*/ }

  # Default action for any controller is "index".
  get ":controller" => "controller#index"

  # Standard routes.
  # BEWARE: This makes all non-private methods available as actions
  get ":controller/:action"
  match ":controller(/:action(/:id))", constraints: { id: /\d+/ },
                                       via: [:get, :post]

  # Accept non-numeric ids for the lookup_xxx actions.
  get ":controller/:action/:id", action: /lookup_\w+/
end

app/models/naming_tracker_email.rb
# Notify user someone has observed a name they are interested in.
class NamingTrackerEmail < AccountMailer
  def build(tracker, naming)
    setup_user(tracker)
    name = "#{naming.observation_id}: #{naming.name.real_search_name}"
    @title = :email_subject_naming_for_tracker.l(name: name)
    @observation = naming.observation
    @naming = naming
    debug_log(:naming_for_observer, nil, tracker,
              naming: naming, observation: naming.observation)
    mo_mail(@title, to: tracker)
  end
end

app/views/naming_tracker_email/build.html.erb
<%
  observation_url = "#{MO.http_domain}/#{@observation.id}"
  name_url        = "#{MO.http_domain}/name/show_name/#{@naming.name_id}"
  observer_url    = "#{MO.http_domain}/observer/show_user/#{@observation.user_id}"
  identifier_url  = "#{MO.http_domain}/observer/show_user/#{@naming.user_id}"

  intro = :email_naming_for_tracker_intro.tp(obs: "xxx", name: "yyy")
  intro.gsub!(/xxx/, link_to(:observation.l, observation_url))
  intro.gsub!(/yyy/, link_to(@naming.format_name.t, name_url))

  fields = ""
  fields += "*#{:Observer.l}:* xxx\n"
  fields += "*#{:Identifier.l}:* yyy\n"
  if @observation.specimen
    fields += "*#{:show_observation_specimen_available.l}*\n"
  else
    fields += "*#{:show_observation_specimen_not_available.l}*\n"
  end
  fields += "*#{:email_field_image_count.l}:* #{@observation.images.length}\n"
  fields = fields.tp
  fields.gsub!(/xxx/, link_to(@observation.user.legal_name, observer_url))
  fields.gsub!(/yyy/, link_to(@naming.user.legal_name, identifier_url))

  handy_links = :email_handy_links.l

  links = []
  links.push([:email_links_show_object.t(type: :observation),
    observation_url])
  links.push([:email_links_show_observer.t,
    observer_url])
  links.push([:email_links_show_identifier.t,
    identifier_url]) if @observation.user_id != @naming.user_id
  links.push([:email_links_disable_tracking.t(type: :name),
    "#{MO.http_domain}/name/email_tracking/#{@naming.name_id}"])
  links.push([:email_links_your_interests.t,
    "#{MO.http_domain}/interest/list_interests"])
  links.push([:email_links_latest_changes.t,
    MO.http_domain])

  report_abuse = :email_report_abuse.l(email: MO.webmaster_email_address)

if @user.email_html %>
<html>
<head>
<title><%= "#{:app_title.t}: #{@title}" %></title>
</head>
<body topmargin=0 leftmargin=0 rightmargin=0 bottommargin=0><br/>
<%= intro.html_safe %>
<%= fields.html_safe %>
<%= handy_links.tp %>
<ul type=none>
  <% for label, url in links %>
    <li><%= label %>: <%= link_to(url, url) %></li>
  <% end %>
</ul>
<%= report_abuse.tp %>
<br/>
</body>
</html>
<% else %><%= intro.html_to_ascii %>

<%= fields.html_to_ascii %>

<%= handy_links.tp.html_to_ascii %>

<%= result = "".html_safe
  for label, url in links
    result += label.html_to_ascii + ": " + url.html_safe + "\n"
  end
  result %>
<%= report_abuse.tp.html_to_ascii %>
<% end %>